PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX cidoc-crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX ctm: <https://lib.ccmusic.edu.cn/ontologies/chinese_traditional_music#>
PREFIX dbpedia-owl: <https://dbpedia.org/ontology/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gn: <https://www.geonames.org/ontology#>
PREFIX juso: <http://rdfs.co/juso/>
PREFIX kanzaki: <http://www.kanzaki.com/ns/music#>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX musicbrainz: <http://musicbrainz.org/ns/mmd-2.0#>
PREFIX opus: <http://lsdis.cs.uga.edu/projects/semdis/opus#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX places: <http://purl.org/ontology/places#>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX relationship: <http://purl.org/vocab/relationship/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tl: <http://purl.org/NET/c4dm/timeline.owl>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
  ?Predicate rdfs:domain ?Subject;
             rdfs:range ?Object.
  ?Subject rdf:type owl:Class;
           rdfs:label ?labelOfSubject;
           rdfs:comment ?commentOfSubject.
  ?Object rdf:type owl:Class;
          rdfs:label ?labelOfObject;
          rdfs:comment ?commentOfObject.
  ?Predicate rdf:type ?PropertyType;
             rdfs:label ?labelOfPredicate;
             rdfs:comment ?commentOfPredicate.
} FROM <http://ont.library.sh.cn/graph/ccmusic_lit_inf> # query the simplified ontology
WHERE {{ #留意这里
  VALUES ?Subject { #这里到时候填上用ChatGPT从自然语言问题中提取的类(translated: This area will be populated with the classes that ChatGPT extracts from natural language questions)
 }
  VALUES ?Object { #这里到时候填上用ChatGPT从自然语言问题中提取的类(translated: This area will be populated with the classes that ChatGPT extracts from natural language questions)

 } 
  VALUES ?Predicate { #这里到时候填上用ChatGPT从自然语言问题中提取的属性(translated: This area will be populated with the properties that ChatGPT extracts from natural language questions)

}
{?Predicate rdfs:domain ?Subject} Union {?Predicate rdfs:domain ?DomainUnion .
    ?DomainUnion rdf:type owl:Class ;
                 owl:unionOf ?UnionList_1 .
    ?UnionList_1 rdf:rest*/rdf:first ?Subject .}
{?Predicate rdfs:range ?Object} Union {?Predicate rdfs:range ?RangeUnion .
    ?RangeUnion rdf:type owl:Class ;
                owl:unionOf ?UnionList_2 .
    ?UnionList_2 rdf:rest*/rdf:first ?Object .}
  }
  optional {?Subject rdfs:label ?labelOfSubject}
  optional {?Subject rdfs:comment ?commentOfSubject}
  optional {?Object rdfs:label ?labelOfObject}
  optional {?Object rdfs:comment ?commentOfObject}
  optional {?Predicate rdfs:label ?labelOfPredicate}
  optional {?Predicate rdfs:comment ?commentOfPredicate}
  optional {?Predicate rdf:type ?PropertyType}
}