# question: 蒙古族有哪些音乐类型_乐种，这些乐种的分布地域各是什么？
# corresponding correct SPARQL
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX ctm: <https://lib.ccmusic.edu.cn/ontologies/chinese_traditional_music#>
PREFIX dbpedia-owl: <https://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?musicTypeLabel ?placeLabel
WHERE {
    ?ethnicGroup rdfs:label "蒙古族" .
    ?ethnicGroup ctm:representativeMusicType ?musicType .
    ?musicType rdfs:label ?musicTypeLabel .
    
    OPTIONAL {
        ?musicType bf:place ?place .
        ?place rdfs:label ?placeLabel .
    }
}
ORDER BY ?musicTypeLabel