# question: 四川扬琴是否有代表性的曲目，这些曲目可能用到了哪些乐器？
# corresponding correct SPARQL
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX ctm: <https://lib.ccmusic.edu.cn/ontologies/chinese_traditional_music#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?pieceLabel ?instrumentLabel WHERE {
  ?musicType a ctm:MusicType ;
             ctm:nameOfMusicTypeOrInstrument "四川扬琴" ;
             ctm:samplePieceWithPerformance ?piece .
  ?piece a ctm:PieceWithPerformance ;
         rdfs:label ?pieceLabel ;
         bf:instrument ?instrument .
  ?instrument rdfs:label ?instrumentLabel .
}