# question: 民间乐人李燕生擅长什么乐种？
# corresponding correct SPARQL
PREFIX ctm: <https://lib.ccmusic.edu.cn/ontologies/chinese_traditional_music#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?musicType ?musicTypeLabel WHERE {
  ?musician a ctm:FolkMusician ;
            rdfs:label "李燕生" ;
            ctm:goodAtPerformingMusic ?musicType .
  ?musicType (rdfs:label | ctm:nameOfMusicTypeOrInstrument) ?musicTypeLabel .
}